version: '3.1'

services:
  camunda:
    container_name: camunda
    image: camunda/camunda-bpm-platform
    ports:
      - 8080:8080
    volumes:
      - "./camunda/camunda-h2-dbs:/camunda/camunda-h2-dbs"
